server:
    port: 8080
    error:
        include-message: always

spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: root
        url: jdbc:postgresql://localhost:5432/armando
        username: postgres
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    servlet:
        multipart:
            enabled: true
            location: uploads/